Yugioh_Card_Manager/Yugioh_Card_Manager/urls.py
import sys, os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('inventory/', include('inventory.urls')),
    path('accounts/', include('accounts.urls'))
]

Yugioh_Card_Manager/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('home', views.index, name='home'),
    path('signup', views.user_signup, name='signup'),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('user_home', views.user_home, name='user_home'),
]

Yugioh_Card_Manager/inventory/urls.py
from django.urls import path
from . import views


app_name = 'inventory'

urlpatterns = [
    path('cards', views.CardsView.as_view(), name='cards'),
    path('monster', views.MonsterAPIView.as_view(), name='monster_create'),
    path('monster/<int:pk>', views.MonsterRudView.as_view(), name='monster_rud'),
    path('magic', views.MagicAPIView.as_view(), name='magic_create'),
    path('magic/<int:pk>', views.MagicRudView.as_view(), name='magic_rud'),
    path('trap', views.TrapAPIView.as_view(), name='trap_create'),
    path('trap/<int:pk>', views.TrapRudView.as_view(), name='trap_rud'),
]

Yugioh_Card_Manager/urls.py
from django.contrib import admin
from django.urls import path, include
from inventory import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include('inventory.urls')),
    path('inventory/', include('django.contrib.auth.urls')),
]

Yugioh_Card_Manager/accounts/models.py
from django.db import models

# Create your models here.

Yugioh_Card_Manager/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core import validators


class SignUpForm(forms.Form):
    username = forms.CharField(min_length=5, max_length=30, required=True, label='Enter username. Between 5-30 characters.')
    first_name = forms.CharField(max_length=30, required=True, label='Enter first name.')
    last_name = forms.CharField(max_length=30, required=True, label='Enter last name.')
    email = forms.EmailField(max_length=100, required=True, label='Enter email.')
    verify_email = forms.EmailField(max_length=100, required=True, label='Confirm email.')
    password = forms.CharField(min_length=5, max_length=100, required=True, widget=forms.PasswordInput, label='Enter password.')
    verify_password = forms.CharField(min_length=5, max_length=100, required=True, widget=forms.PasswordInput, label='Confirm password.')

    field_order = ['verify_email', 'verify_password']

    def clean_username(self):
        username = self.cleaned_data['username']
        res = User.objects.filter(username=username)
        if res:
            raise forms.ValidationError("Username already exists.")
        return username
    
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        verify_email = self.cleaned_data['verify_email'].lower()
        res = User.objects.filter(email=email)

        if email != verify_email:
            raise forms.ValidationError("Make sure emails match.")
        if res:
            raise forms.ValidationError("Email already exists.")
        return email

    def clean_password(self):
        password = self.cleaned_data['password']
        verify_password = self.cleaned_data['verify_password']

        if password and verify_password and password != verify_password:
            raise forms.ValidationError("Make sure passwords match.")
        return password

    def save(self):
        clean_data = super(SignUpForm, self).clean()
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password'],
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name']
        )
        return user

Yugioh_Card_Manager/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import SignUpForm


def index(request):
    """
    View for website home page.
    """
    return render(request, 'accounts/home.html')

def user_signup(request):
    """
    View for sign up page.
    """
    if request.method == 'POST':
        signup_form = SignUpForm(request.POST)
        if signup_form.is_valid():
            user = signup_form.save()
            # Creates hashed password from raw password
            user.set_password(signup_form.cleaned_data['password'])
            user.save()
            return render(request, 'accounts/signup_success.html')
    else:
        signup_form = SignUpForm()
    return render(request, 'accounts/signup.html', {'signup_form': signup_form})

def user_login(request):
    """
    View for login page.
    """
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        try:
            user = User.objects.get(username=username)
            if user.check_password(password):
                login(request, user)
                # TODO: use redirect to different url instead of render
                return render(request, 'accounts/user_home.html')
            else:
                # TODO: fix message display (clear it after each run)
                messages.error(request, 'Invalid authentication. Please try again.')
        except Exception as e:
            messages.error(request, 'User does not exist. Please try again.')
    return render(request, 'accounts/login.html')

def user_home(request):
    """
    View for user home page.
    """
    # TODO: Check if user homepage is displayed only when authenticated.
    # (Right now renders the page when we click 'Back' from 'View all cards'.)
    return render(request, 'accounts/user_home.html')

def user_logout(request):
    """
    View for logout page.
    """
    logout(request)
    return render(request, 'accounts/logout_success.html')

Yugioh_Card_Manager/templates/accounts/home.html
{% extends "base.html" %}

{% block title %}Yu-Gi-Oh! Card Manager{% endblock %}

{% block content %}
<h1>Yu-Gi-Oh! Card Manager Homepage</h1>
<p>This website allows you to manage your Yu-Gi-Oh! cards and build your dream decks.</p>
<form action="/accounts/login">
    <input type="submit" value="Click here to login.">
</form>
<form action="/accounts/signup">
    <input type="submit" value="Click here to signup.">
</form>
{% endblock %}

Yugioh_Card_Manager/templates/accounts/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<h1>Login</h1>
<div class="container">
    <form action="/accounts/login" method="post">
        {% csrf_token %}
        {% for message in messages %}<p style="color: crimson;">{{ message }}</p>{% endfor %}
        <label for="username">Username: </label>
        <input id="username" type="text" name="username" placeholder="Username" required>

        <label for="password">Password: </label>
        <input id="password" type="password" name="password" placeholder="Password" required>

        <input type="submit" value="Login">
    </form>
</div>
<form action="/accounts/home">
    <input type="submit" value="Return to homepage.">
</form>
{% endblock %}

Yugioh_Card_Manager/templates/accounts/logout_success.html
{% extends "base.html" %}

{% block title %}Logout Success{% endblock %}

{% block content %}
<h1>Successfully logged out!</h1>
<form action="/accounts/home">
    <input type="submit" value="Click here to go to homepage.">
</form>
<form action="/accounts/login">
    <input type="submit" value="Click here to go to login again.">
</form>
{% endblock %}

Yugioh_Card_Manager/templates/accounts/signup.html
{% extends "base.html" %}

{% block title %}Account Sign Up{% endblock %}

{% block content %}

<h1>Account Sign Up</h1>
<p>Please fill in the form. All fields are required.</p>

<div class="container">
    <form action="/accounts/signup" method="post" id="signup_form">
        {% csrf_token %}
        {% for field in signup_form %}
            {% for error in field.errors %}
                <p style="color: crimson;">{{ error }}</p>
            {% endfor %}
        {% endfor %}
        <label for="username">Username: </label>
        <input id="username" type="text" name="username" placeholder="Username" required>

        <label for="first_name">First Name: </label>
        <input id="first_name" type="text" name="first_name" placeholder="First Name" required>

        <label for="last_name">Last Name: </label>
        <input id="last_name" type="text" name="last_name" placeholder="Last Name" required>

        <label for="email">Email: </label>
        <input id="email" type="email" name="email" placeholder="Email" required>

        <label for="verify_email">Verify Email: </label>
        <input id="verify_email" type="email" name="verify_email" placeholder="Verify Email" required>

        <label for="password">Password: </label>
        <input id="password" type="password" name="password" placeholder="Password" required>

        <label for="verify_password">Verify Password: </label>
        <input id="verify_password" type="password" name="verify_password" placeholder="Verify Password" required>
        
        <input type="submit" value="Submit">
    </form>
</div>
<form action="/accounts/home">
    <input type="submit" value="Return to homepage.">
</form>
{% endblock %}

Yugioh_Card_Manager/templates/accounts/signup_success.html
{% extends "base.html" %}

{% block title %}Signup Success{% endblock %}

{% block content %}
<h1>Successfully signed up!</h1>
<form action="/accounts/login">
    <input type="submit" value="Click here to login.">
</form>
{% endblock %}

Yugioh_Card_Manager/templates/accounts/user_home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    Hello {{ user.username }}!

    <form action="{% url 'inventory:cards' %}" method="get">
        {% csrf_token %}
        <input type="submit" value="View all cards">
    </form>

    <form action="{% url 'inventory:monster_create' %}" method="get">
        {% csrf_token %}
        <input type="submit" value="Create monster cards">
    </form>

    <form action="{% url 'inventory:magic_create' %}" method="get">
        {% csrf_token %}
        <input type="submit" value="Create magic cards">
    </form>

    <form action="{% url 'inventory:trap_create' %}" method="get">
        {% csrf_token %}
        <input type="submit" value="Create trap cards">
    </form>

    <form action="/accounts/logout" method="post">
        {% csrf_token %}
        <input type="submit" value="Logout">
    </form>
{% endif %}
{% endblock %}